### ISSUE TITLE
Deprecate implementation

### ISSUE THREAD

**Issue by uniqueg** [microsoft/tes-azure#31]
## Problem

This service has not been updated since [August 2022](https://github.com/microsoft/tes-azure/commit/11b3b4d2d40f73c4e758c99629ae6dd1b815465d), with the last non-cecurity- or policy-related update dating back to [May 2019](https://github.com/microsoft/tes-azure/commit/6ac3207e4f4c57dd65974b61842fdda0f5f9741c). [PRs for security updates](https://github.com/microsoft/tes-azure/pulls) have not been merged for more than a year, at the time of writing.

Moreover, a new [Microsoft implementation](https://github.com/microsoft/ga4gh-tes) for the [GA4GH TES API](https://github.com/ga4gh/task-execution-schemas) on Azure has since been [released](https://github.com/microsoft/ga4gh-tes/releases) and receives [regularl updates](https://github.com/microsoft/ga4gh-tes/graphs/code-frequency). Yet, online searches for relevant keywords may still bring up this project, which may potentially mislead people interested in Microsoft's efforts to implement the GA4GH TES specification for Azure.

## Solution

To clearly mark this service as deprecated/outdated:

1. Add an depreciation warning to the top of the `README.md` of this repository, informing users to instead visit <https://github.com/microsoft/ga4gh-tes>
2. Add repository topics `deprecated` and/or `obsolete`
3. Archive the repository

Optionally, this repository could be renamed (e.g., to `microsoft/tes-azure-legacy`) before archiving and the new repository (currently `microsoft/ga4gh-tes`) could be renamed to `microsoft/tes-azure`. In this way, both https://github.com/microsoft/tes-azure and https://github.com/microsoft/ga4gh-tes would resolve to the new implementation at this location.

@MattMcL4475 @vsmalladi

**Comment by erikhoward** [comment]
All suggested changes have been made. Repo has also been renamed to tes-azure-legacy.
